version: "3"
services:
  postgres_test:
    image: "postgres:9.6"
    container_name: "postgres_test"
    environment:
      - POSTGRES_USER=sqlalch
      - POSTGRES_PASSWORD=sqlalch
      - POSTGRES_DB=sqlalch
    ports:
      - "5433:5433"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  main:
    build: .
    image: sqlalch.web:dev
    command: python3.7 sqlalchan/example/db.py
    environment:
      - DB_USER=sqlalch
      - DB_PASS=sqlalch
      - DB=sqlalch
    depends_on:
      - postgres_test
    volumes:
      - ./:/main


